server:
  port: 8761 # must be 8761 if not error
spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
#      defaultZone: http://106.52.119.173:8761/eureka
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://peer1:8761/eureka, http://peer2:8762/eureka
    fetch-registry: true #fetch have been registried service's list
    register-with-eureka: true #?????????????? ???????

  server:
    eviction-interval-timer-in-ms: 90000 #????????????? -- ????
    enable-self-preservation: true #server ?????????????????????,????????
    renewal-percent-threshold: 0.85 #85%????????? client ??15 ???? 85%? client ?????






  instance:
#    hostname: biluo.cloud #??????
    hostname: localhost #??????
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true #?????ip?????
    lease-renewal-interval-in-seconds: 10     # ?? eureka client ????? server ????
    lease-expiration-duration-in-seconds: 90  #?? eureka server ?????? client ?????????????????
                                              # ?????????????????????????

